apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  containers:
  - name: golang
    image: localhost:32000/golang:alpine3.16
    command:
    - cat
    tty: true
  - name: maven
    image: localhost:32000/maven:3.8.5-openjdk-18
    command:
    - cat
    tty: true
  - name: python
    image: localhost:32000/python:latest
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    restartPolicy: Never
    volumes:
    - name: kaniko-secret
      secret:
          secretName: dockercred
          items:
          - key: .dockerconfigjson
            path: config.json

---
apiVersion: v1
kind: Secret
metadata:
  name: dockercred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0YW5nam9lODgiLCJwYXNzd29yZCI6InBhc3N3MHJkIiwiZW1haWwiOiJ0YW5nd2Nqb2VAZ21haWwuY29tIiwiYXV0aCI6ImRHRnVaMnB2WlRnNE9uQmhjM04zTUhKayJ9fX0=
type: kubernetes.io/dockerconfigjson
