apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  containers:
  - name: golang
    image: golang:alpine3.16
    command:
    - cat
    tty: true
  - name: maven
    image: maven:3.8.5-openjdk-18
    command:
    - cat
    tty: true
  - name: python
    image: python:latest
    command:
    - cat
    tty: true
